### ISSUE TITLE
Sometimes CI fails with timeout

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/jstp#327]
But it finished with success after restart
FYI: @nechaido @belochub 
```
not ok 8 - test/node/connection-emit-actions.js # time=20622.999ms
  ---
  timeout: 240000
  file: test/node/connection-emit-actions.js
  command: /home/travis/.nvm/versions/node/v8.9.4/bin/node
  args:
    - test/node/connection-emit-actions.js
  stdio:
    - 0
    - pipe
    - 2
  cwd: /home/travis/build/metarhia/jstp
  exitCode: 1
```
